'use client';
import { useState } from 'react';
import { BookOpen, Download, Shield, TestTube, Code, Lightbulb, ExternalLink } from 'lucide-react';
import { Card } from '@/components/ui/Card';
import { Badge, severityVariant } from '@/components/ui/Badge';
import { Button } from '@/components/ui/Button';

export function KnowledgeCardPanel({ incident }: { incident: any }) {
  const kc = incident.knowledgeCard;

  if (!kc) {
    return (
      <div className="text-center py-12 text-forge-muted text-sm">
        Knowledge Card will be generated after investigation completes.
      </div>
    );
  }

  function exportCard() {
    const text = `# Incident Knowledge Card

**Incident ID:** ${incident.incidentId}
**Title:** ${incident.title}
**Severity:** ${incident.severity}
**Date:** ${incident.createdAt}

## Root Cause
${kc.rootCauseSummary}

## Affected Components
${JSON.parse(kc.affectedComponents || '[]').join(', ')}

## Affected Files
${JSON.parse(kc.affectedFiles || '[]').join(', ')}

## Fix Summary
${kc.fixSummary}

## Tests Added
${kc.testsAdded}

## Security Status
${kc.securityStatus}

## Review Outcome
${kc.reviewOutcome}

## Verification
${kc.verificationStatus}

## Prevention Recommendations
${JSON.parse(kc.preventionRecommendations || '[]').map((r: string, i: number) => `${i+1}. ${r}`).join('\n')}

## Similar Patterns
${JSON.parse(kc.similarPatterns || '[]').join(', ')}

## Notes
${kc.documentationNotes}

---
Generated by TraceForge
`;
    const blob = new Blob([text], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `knowledge-card-${incident.incidentId}.md`;
    a.click();
  }

  const prevention = parseJson(kc.preventionRecommendations);
  const similar = parseJson(kc.similarPatterns);
  const components = parseJson(kc.affectedComponents);
  const files = parseJson(kc.affectedFiles);

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <BookOpen size={16} className="text-forge-accent" />
          <h3 className="text-sm font-semibold">Incident Knowledge Card</h3>
        </div>
        <Button variant="secondary" size="sm" icon={<Download size={12} />} onClick={exportCard}>
          Export Markdown
        </Button>
      </div>

      {/* Header */}
      <div className="bg-forge-surface border border-forge-border rounded-lg p-4 grid grid-cols-2 md:grid-cols-4 gap-3">
        <KV label="Incident ID" value={<span className="font-mono text-forge-accent">{incident.incidentId}</span>} />
        <KV label="Severity" value={<Badge variant={severityVariant(incident.severity)}>{incident.severity}</Badge>} />
        <KV label="Review Outcome" value={<Badge variant={severityVariant(kc.reviewOutcome)}>{kc.reviewOutcome?.replace(/_/g, ' ')}</Badge>} />
        <KV label="Verification" value={<Badge variant={kc.verificationStatus === 'VERIFIED' ? 'success' : 'warning'}>{kc.verificationStatus}</Badge>} />
      </div>

      <Card>
        <div className="text-xs text-forge-muted font-medium mb-2">Root Cause Summary</div>
        <p className="text-sm leading-relaxed">{kc.rootCauseSummary}</p>
      </Card>

      <div className="grid grid-cols-2 gap-4">
        <Card>
          <div className="text-xs text-forge-muted font-medium mb-2">Affected Components</div>
          {components.map((c: string) => (
            <div key={c} className="text-sm text-forge-text bg-forge-bg rounded px-2 py-1 mb-1">{c}</div>
          ))}
        </Card>
        <Card>
          <div className="text-xs text-forge-muted font-medium mb-2">Affected Files</div>
          {files.map((f: string) => (
            <div key={f} className="font-mono text-xs text-forge-accent bg-forge-bg rounded px-2 py-1 mb-1">{f}</div>
          ))}
        </Card>
      </div>

      <div className="grid grid-cols-3 gap-3">
        <Card>
          <div className="flex items-center gap-1.5 mb-1">
            <Code size={12} className="text-forge-muted" />
            <span className="text-xs text-forge-muted">Fix</span>
          </div>
          <p className="text-sm">{kc.fixSummary}</p>
        </Card>
        <Card>
          <div className="flex items-center gap-1.5 mb-1">
            <TestTube size={12} className="text-green-400" />
            <span className="text-xs text-forge-muted">Tests Added</span>
          </div>
          <div className="text-2xl font-semibold text-green-400">{kc.testsAdded}</div>
        </Card>
        <Card>
          <div className="flex items-center gap-1.5 mb-1">
            <Shield size={12} className="text-blue-400" />
            <span className="text-xs text-forge-muted">Security</span>
          </div>
          <Badge variant={kc.securityStatus === 'PASSED' ? 'success' : 'warning'}>
            {kc.securityStatus?.replace(/_/g, ' ')}
          </Badge>
        </Card>
      </div>

      {/* Prevention */}
      {prevention.length > 0 && (
        <Card>
          <div className="flex items-center gap-2 mb-3">
            <Lightbulb size={14} className="text-yellow-400" />
            <span className="text-sm font-semibold">Prevention Recommendations</span>
          </div>
          <ul className="space-y-2">
            {prevention.map((rec: string, i: number) => (
              <li key={i} className="flex items-start gap-2 text-sm">
                <span className="text-forge-accent font-mono text-xs mt-0.5 flex-shrink-0">{i+1}.</span>
                {rec}
              </li>
            ))}
          </ul>
        </Card>
      )}

      {/* Similar patterns */}
      {similar.length > 0 && (
        <Card>
          <div className="text-xs text-forge-muted font-medium mb-2">Similar Bug Patterns</div>
          <div className="flex flex-wrap gap-2">
            {similar.map((p: string) => (
              <span key={p} className="px-2 py-1 bg-forge-bg border border-forge-border rounded text-xs text-forge-muted">{p}</span>
            ))}
          </div>
        </Card>
      )}

      {kc.documentationNotes && (
        <Card>
          <div className="text-xs text-forge-muted font-medium mb-1.5">Notes</div>
          <p className="text-sm text-forge-muted">{kc.documentationNotes}</p>
        </Card>
      )}
    </div>
  );
}

function KV({ label, value }: { label: string; value: React.ReactNode }) {
  return (
    <div>
      <div className="text-xs text-forge-muted mb-1">{label}</div>
      <div className="text-sm">{value}</div>
    </div>
  );
}

function parseJson(val: any): any[] {
  if (Array.isArray(val)) return val;
  try { return JSON.parse(val || '[]'); } catch { return []; }
}
